[package]
name = "day_2021_0130"
version = "0.1.0"
authors = ["holdnosoul <holdnosoul@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leveldb = "0.8.5"
